### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by davelab6** [peterkeen/ledger-web#14]
Why did this project stop being developed?

What alternatives could you recommend? :)

**Comment by peterkeen** [comment]
I still use it every day, so I wouldn't say it has stopped being developed. It's just "done," I guess.

There are a number of alternatives. [hledger](http://hledger.org/) has it's own built-in web interface and there's another one named [ledgible](https://github.com/lipidity/ledgible) that may be interesting.

**Comment by davelab6** [comment]
Awesome, thanks!
